### ISSUE TITLE
Enable to load grid2op data with pickle

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#376]
## Environment
 - Grid2op version: `1.7.2`
 - System: `ubuntu20.04, ...`

## Bug description
From grid2op version 1.7.1, trying in grid2viz to load with pickle a "dill" dump of grid2op data fails and return "AttributeError: type object 'ActionWCCI2022_input_data_test' has no attribute 'process_grid2op_shunt_data". Works in 1.7.0

Is there a typo in "process_grid2op_shunt_data" here https://github.com/rte-france/Grid2Op/blob/51854262d02d96c1ee1798a78a86661d1ff971a1/grid2op/Space/GridObjects.py#L3742 ? As the method does not seem to exist in grid2op package, but "process_shunt_data" exists. Replacing by "process_shunt_data" does not raise the error anymore and let the loading with pickle runs fine.

### Code snippet

```python
import grid2op

... # Some code 
import pickle
import gzip
pickle.load(gzip.open("pathTo/maze-rl_only_topo_2050-01-10_1.dill.bz", "rb"))
```
Here is the file to unzip to reproduce it
[maze-rl_only_topo_2050-01-10_1.zip](https://github.com/rte-france/Grid2Op/files/10092777/maze-rl_only_topo_2050-01-10_1.zip)

**Comment by BDonnot** [comment]
Duplicate of #365
