### PR TITLE
WIP: Flexibile Loads

### PR DESCRIPTION
**Pull request by DEUCE1957**
**Warning**: Work In Progress (WIP) so do not accept this Pull Request yet.

Attempt to extend Redispatching by enabling Environment's to have flexible loads. See "getting_started" / "12_Flexibility.ipynb" for example use. Related to issue #623 (will move onto load / generator shedding once this works).

Currently working:
1. Able to define "flexibility" actions (env.action_space({"flexibility":[("load_0_0", 0.1]}) with correct print string for BaseAction
2. Able to load flexible load attributes from "flex_loads_charac.csv"
3. "InvalidFlexibility" error if flexibility exceeds size of load

Not yet working:
1. Observable change in load after executing flexibility action in environment
2. Observable change in actual/target flexibility after executing flexibility action in environment
3. Integration with redispatch routine (currently a seperate objective function)
4. Automated tests (need new ones, currently manually testing with notebook)

### CODE REVIEW

**Comment by DEUCE1957** [comment]
Most tests passing now, remaining error (in ci/circleci:test) appears to be from CI itself:

`======================================================================
ERROR: test_alert_gym_compat (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: type object '_FailedTest' has no attribute 'test_alert_gym_compat'

----------------------------------------------------------------------`

Appreciate any review / feedback to solve this.

**Comment by BDonnot** [comment]
Hello,

Sorry for the delay.

This is so weird. I'll check the CI ASAP

**Comment by BDonnot** [comment]
Hello,

I think the CI is working on the dev_1.10.4 now, can you synch and see if it solves your issue ?

**Comment by DEUCE1957** [comment]
Afraid I am still getting the same error as above for the CI.

File: getting_started/12_flexibility.ipynb [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+  {
+   "cell_type": "markdown",
+   "metadata": {},
+   "source": [
+    "## Flexibility and Shedding\n",
+    "By default, an episode ends if one of the following conditions is met:\n",
+    "1. **End of Chronics**: The agent reaches the end of the chronics (timeseries) for an Episode (no more data => scenario ends)\n",
+    "2. **Disconnected Generator / Load**: A load, generator is disconnected from the grid. This also applies to Energy Storage Systems (ESSs) if they are being controlled (agent told it to charge / discharge some energy)\n",
+    "3. **Islanding**: The grid splits into multiple parts / islands. For example, a load of generator is alone on a busbar. \n",
+    "4. **Powerflow Divergence**: The redispatching routine \"diverges\": this means that Grid2OP is not able to find a setpoint for the generators for which both \"pmin, pmax and the ramps constrained\" as well as the \"load / generator balancing the solver \"diverges\" and is not able to compute the next state (often meaning there are no feasible solutions to the Kirchoff's laws)\n",
```
Comment (BDonnot) [inline getting_started/12_flexibility.ipynb:12]: I'll try to update the doc but actually point 4 above is two different things:

- either the backend diverge (cannot compute the flows, no feasible solution found)
- or the "grid2op routine" to compute the "redispatching" fails

It is two distinct things.

File: grid2op/tests/test_defaultgym_compat.py [hunk 2]
```diff
@@ -6,7 +6,9 @@
 # SPDX-License-Identifier: MPL-2.0
 # This file is part of Grid2Op, Grid2Op a testbed platform to model sequential decision making in power systems.
 
-
+import sys
+from pathlib import Path
+sys.path.append(str(Path(__file__).parent))
```
Comment (BDonnot) [inline grid2op/tests/test_defaultgym_compat.py:11]: I would avoid doing that if possible

File: grid2op/tests/test_gymnasium_compat.py [hunk 3]
```diff
@@ -5,8 +5,9 @@
 # you can obtain one at http://mozilla.org/MPL/2.0/.
 # SPDX-License-Identifier: MPL-2.0
 # This file is part of Grid2Op, Grid2Op a testbed platform to model sequential decision making in power systems.
-
-
+import sys
+from pathlib import Path
+sys.path.append(str(Path(__file__).parent))
```
Comment (BDonnot) [inline grid2op/tests/test_gymnasium_compat.py:10]: It was not necessary before, and tests used to pass on the CI, maybe this is what caused the issue. Can you remove all these changes in the test suite and run it again ?

**Comment by BDonnot** [comment]
Hi,

I see you added
```python
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent))
```

In a lot of files. That should not be necessary (did not used to be there when tests passed). Have you tried to remove it and see if tests pass ? Maybe you are missing the gym / gymnasium import when you do that (it's in general not a good idea to "mess with" python sys.path, it often leads to weird behaviour). Maybe it's not the cause of the problem, but maybe it is :-)

**Comment by BDonnot** [comment]
Also (to keep track of it, I noticed it and did not want to "discover this again later")

I think you did not update the https://grid2op.readthedocs.io/en/latest/modeled_elements.html page of the doc nor the https://grid2op.readthedocs.io/en/latest/mdp.html, for example https://grid2op.readthedocs.io/en/latest/mdp.html#action-space or https://grid2op.readthedocs.io/en/latest/mdp.html#state-space

File: grid2op/tests/test_gymnasium_compat.py (hunk 3 above)
Comment (DEUCE1957) [reply grid2op/tests/test_gymnasium_compat.py:10]: Trying that now :)

**Comment by BDonnot** [comment]
Hello,

I fixed the issues caused by the install of gymnasium 1.0 in dev_1.10.4, I think once you'll have synched this will no longer be an issue :-)

Benjamin

**Comment by DEUCE1957** [comment]
Closing due to migration to dev_1.11.0. 
See new Pull Request: [https://github.com/Grid2op/grid2op/pull/628](https://github.com/Grid2op/grid2op/pull/628)
